version: '3'
services:
    core_api:
        build: .
        container_name: "crm-admin-api"
        ports:
            - "8014:15400"
        volumes:
            - ./app/:/app
        environment:
          - GOOGLE_APPLICATION_CREDENTIALS="app/credentials.json"

